environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script interpreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C run_with_env.cmd"

  matrix:
    - PYTHON_VERSION: 3.5
      PYTHON_ARCH: "32"
      MINICONDA: C:\Miniconda35
    - PYTHON_VERSION: 3.5
      PYTHON_ARCH: "64"
      MINICONDA: C:\Miniconda35-x64
    - PYTHON_VERSION: 3.6
      PYTHON_ARCH: "32"
      MINICONDA: C:\Miniconda36
    - PYTHON_VERSION: 3.6
      PYTHON_ARCH: "64"
      MINICONDA: C:\Miniconda36-x64

build: false

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels defaults
  - conda update -q --all
  - conda install conda-build numpy anaconda-client
  # build
  - conda build --skip-existing conda-recipe

on_success:
  - anaconda -t %CONDA_TOKEN% upload %MINICONDA%\\conda-bld\\win-%PYTHON_ARCH%\\*.tar.bz2