
package:
    name: archiveexport
    version: 0.9.1

source:    
    path: ..

requirements:
  build:
    - {{ compiler('cxx') }}
    - make

  host:
    - python
    - epics-base

  run:
    - python
    - epics-base

about:
    home: http://www.aps.anl.gov/epics
    license: Epics Open License
    summary: EPICS Base Library
