
package:
    name: archiveexport
    version: 0.9.1

source:    
    path: ..

requirements:
  build:
    - {{ compiler('cxx') }}
    - make

  host:
    - python
    - epics-base

  run:
    - python
    - epics-base

about:
    home: https://github.com/paulscherrerinstitute/archiveexport
    license: GNU GENERAL PUBLIC LICENSE Version 3
    summary: EPICS Base Library
